# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 17:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('resume', models.FileField(upload_to='')),
                ('permanent_address', models.CharField(max_length=250)),
                ('pan', models.CharField(max_length=20)),
                ('hr', models.BooleanField(default=False)),
                ('passport_no', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('employee_gmail', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Employee_Gmail')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_logo', models.FileField(upload_to='')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7543036718'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('emergency_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7543036718'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('emergency_contact_number1', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7543036718'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('current_address', models.CharField(max_length=250)),
                ('field_of_intrest', models.CharField(max_length=100)),
                ('employee_gmail', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Employee_Gmail')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=6)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('interviewer_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewee_name', models.CharField(max_length=250)),
                ('interviewee_email_id', models.EmailField(max_length=250)),
                ('interviewee_resume', models.FileField(upload_to='')),
                ('job_profile', models.CharField(default='Not Set', max_length=200)),
                ('status', models.CharField(default='Interview not yet done', max_length=100)),
                ('employee_gmail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Employee_Gmail')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechicle_type', models.CharField(max_length=20)),
                ('vechicle_model', models.CharField(max_length=30)),
                ('vechicle_number', models.CharField(max_length=30)),
                ('employee_gmail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Employee_Gmail')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='interviewee_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='box.Interviewee'),
        ),
    ]
