# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='level',
        ),
    ]
