# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_remove_feedback_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='level',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
